apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - asciidoc.yaml
  - git.yaml
  - gmake.yaml
  - home.yaml
  - k8s.yaml
  - keyhole.yaml
  - lima.yaml
  - nix.yaml
  - xdg.yaml
